require('dotenv').config();const express=require('express');const {fork}=require('child_process');const path=require('path');
const PORT=Number(process.env.PORT||10000);let BOT_ID=Number(process.env.BOT_ID||0);const MASTER_URL=String(process.env.MASTER_URL||'').replace(/\/$/,''),AGENT_SECRET=String(process.env.AGENT_SECRET||'');
if(!AGENT_SECRET)console.warn('⚠️ Configure AGENT_SECRET no Render deste Agent. BOT_ID é opcional.');
const app=express();app.use(express.json({limit:'512kb'}));let child=null,currentConfig=null,logs=[],status={reachable:true,running:false,online:false,phase:'offline',lastReason:'',startedAt:null,pid:null};
function addLog(x){const line=`[${new Date().toISOString()}] ${String(x).trim()}`;logs.push(line);while(logs.length>180)logs.shift();console.log(line);heartbeat(String(x).trim()).catch(()=>{})}
function auth(req,res,next){const got=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(got!==AGENT_SECRET)return res.status(403).json({ok:false,error:'Agent Secret inválido'});next()}
function setStatus(p){status={...status,...p,reachable:true,lastChangeAt:new Date().toISOString()}}
function childMessage(m={}){if(m.type==='SL_ONLINE')setStatus({running:true,online:true,phase:'online',lastReason:''});if(m.type==='SL_CONNECTING')setStatus({running:true,online:false,phase:'connecting',lastReason:'Conectando...'});if(m.type==='SL_OFFLINE')setStatus({running:!!child,online:false,phase:m.payload?.phase||'offline',lastReason:m.payload?.reason||'Offline'})}
function start(config){if(child)return {ok:true,message:'Bot já está ligado.'};if(config)currentConfig=config;if(!currentConfig)throw new Error('Configuração do bot não carregada.');const safe={...currentConfig};delete safe.agentSecret;delete safe.renderApiKey;const env={...process.env,BOT_ID:String(BOT_ID),BOT_CONFIG_B64:Buffer.from(JSON.stringify(safe)).toString('base64')};child=fork(path.join(__dirname,'botsl.js'),[],{silent:true,env});setStatus({running:true,online:false,phase:'starting',lastReason:'Processo iniciado',startedAt:new Date().toISOString(),pid:child.pid});addLog('🚀 Processo do bot iniciado.');child.stdout.on('data',d=>addLog(d));child.stderr.on('data',d=>addLog(d));child.on('message',childMessage);child.on('exit',c=>{addLog(`🛑 Processo finalizado código ${c}`);child=null;setStatus({running:false,online:false,phase:'offline',pid:null,lastReason:`Processo finalizado código ${c}`});setTimeout(()=>bootstrap(true).catch(e=>addLog('Bootstrap após queda: '+e.message)),8000)});return {ok:true,message:'Bot ligado.'}}
function stop(){if(!child){setStatus({running:false,online:false,phase:'offline'});return {ok:true,message:'Bot já está desligado.'}}const c=child;child=null;try{c.kill('SIGTERM')}catch{}setStatus({running:false,online:false,phase:'offline',pid:null,lastReason:'Desligado pelo painel'});addLog('⏹️ Bot desligado pelo painel.');return {ok:true,message:'Bot desligado.'}}
function restart(config){stop();if(config)currentConfig=config;return start(currentConfig)}
function send(type,payload={}){if(!child)return {ok:false,error:'Bot desligado.'};if(!status.online)return {ok:false,error:`Bot ainda não está online. Status: ${status.phase}`};child.send({type,payload});addLog('📨 '+type);return {ok:true,message:'Comando enviado.'}}
async function bootstrap(autoStart=true){if(!MASTER_URL||!AGENT_SECRET)return;const r=await fetch(MASTER_URL+'/api/agent/bootstrap',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({botId:BOT_ID,agentSecret:AGENT_SECRET,status})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`Master HTTP ${r.status}`);BOT_ID=Number(d.botId||d.config?.id||BOT_ID);currentConfig=d.config;if(autoStart&&d.desiredOnline&&!child)start(currentConfig);if(!d.desiredOnline&&child)stop();return d}
async function heartbeat(log){if(!MASTER_URL||!AGENT_SECRET)return;try{const r=await fetch(MASTER_URL+'/api/agent/heartbeat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({botId:BOT_ID,agentSecret:AGENT_SECRET,status,log:log||''})});if(r.ok){const d=await r.json();if(d.desiredOnline===false&&child)stop();}}catch{}}
app.get('/',(_q,r)=>r.json({ok:true,agent:'SL Bot Agent',botId:BOT_ID,status}));app.get('/health',(_q,r)=>r.send('ok'));
app.get('/status',auth,(_q,r)=>r.json({ok:true,status}));app.get('/logs',auth,(_q,r)=>r.json({ok:true,logs}));
app.post('/start',auth,(q,r)=>{try{r.json(start(q.body?.config))}catch(e){r.status(400).json({ok:false,error:e.message})}});app.post('/stop',auth,(_q,r)=>r.json(stop()));app.post('/restart',auth,(q,r)=>{try{r.json(restart(q.body?.config))}catch(e){r.status(400).json({ok:false,error:e.message})}});app.post('/home',auth,(_q,r)=>r.json(send('GO_HOME')));app.post('/invite',auth,(q,r)=>r.json(send('GROUP_INVITE',q.body||{})));
app.listen(PORT,'0.0.0.0',()=>{console.log(`✅ Agent do bot ${BOT_ID||'?'} ativo na porta ${PORT}`);bootstrap(true).catch(e=>addLog('Bootstrap: '+e.message));setInterval(()=>heartbeat().catch(()=>{}),60000)});
process.on('SIGTERM',()=>{try{if(child)child.kill('SIGTERM')}catch{}process.exit(0)});
